#!/bin/sh

# Reload nginx configuration every 24 hours in background.
# This is needed in order to use the renewed SSL certificate generated by certbot.
while :
do
    sleep 24h
    nginx -s reload &>/dev/null
done &

service cron start && nginx -g 'daemon off;'