# Example Nginx Configuration for nginx1/nginx.conf
events{}
http{
  server {
    listen 80;
    server_name localhost;

    root /var/www/html;
    index index.php index.html;

    location / {
      # Try to serve index.php
      try_files $uri $uri/ /index.php?$query_string;
    }

    # add location for php files 
    location ~ \.php$ {
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

      # Pass original client info to PHP
      fastcgi_param HTTP_X_REAL_IP        $remote_addr;
      fastcgi_param HTTP_X_FORWARDED_FOR  $proxy_add_x_forwarded_for;
      fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;

      fastcgi_param REMOTE_ADDR $remote_addr;
      fastcgi_pass php-nginx1:9000;
    }
  }
}