


events {}
http {
    server {
        listen 80;
        server_name localhost;

        root /var/www/html;
        index index.php index.html;

        # First step - Turnstile gateway
        location / {
            if ($http_cookie !~* "verified=true") {
                return 302 /verify-captcha;
            }
            if ($http_cookie ~* "verified=true") {
                add_header X-Verified "true" always;
            }

            # Try to serve index.php
            try_files $uri $uri/ /index.php?$query_string;
        }

        # add location for php files 
        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            # Pass original client info to PHP
            fastcgi_param HTTP_X_REAL_IP        $remote_addr;
            fastcgi_param HTTP_X_FORWARDED_FOR  $proxy_add_x_forwarded_for;
            fastcgi_param HTTP_X_FORWARDED_PROTO $scheme;

            
            fastcgi_param REMOTE_ADDR $remote_addr;

            fastcgi_pass php-nginx6:9000;
        }

        location /verify-captcha {
            alias /usr/share/nginx/html/gateway;
            index index.html;
        }

        # Second step - Backend API for verification
        location /verify-turnstile {
            proxy_pass http://captcha-turnstile-backend:3002/verify-turnstile;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
    }
}
